apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: orionispaxpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orionispaxpipelinesjavascriptdocker 
    spec:
      containers:
        - name: orionispaxpipelinesjavascriptdocker 
          image: samplecr.azurecr.io/orionispaxpipelinesjavascriptdocker
          ports:
          - containerPort: 8080